services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=nitrotech'
      - 'POSTGRES_USER=nitrotech'
      - 'POSTGRES_PASSWORD=nitrotech'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
