package com.nitrotech.api.domain.audit;

public enum AuditAction {
    ROLE_UPDATED,
    ROLE_PERMISSION_UPDATED,
    USER_ROLE_UPDATED,
    SHIPMENT_CREATED,
    SHIPMENT_SIMULATION_EVENT,
    SHIPMENT_WEBHOOK_RECEIVED,
    ORDER_STATUS_UPDATED,
    ORDER_CANCELLED,
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    USER_STATUS_UPDATED,
    USER_DELETED,
    USER_RESTORED
}
